// Demo product data matching zeelool.com real products
export const demoProducts = [
  {
    id: 'ZJGA463908-02',
    name: 'Patrick Glasses',
    price: 15.00,
    rating: 4.0,
    image: '/demo-products/product-1.jpg',
    colors: [
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
      { name: 'Yellow', hex: '#FFD700', img: '/demo-products/colors/gold.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
    ],
    href: '/products/patrick-glasses',
  },
  {
    id: 'ZJGA294199-01',
    name: 'Robert Glasses',
    price: 19.95,
    rating: 4.3,
    image: '/demo-products/product-2.jpg',
    colors: [
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
      { name: 'Brown', hex: '#654321', img: '/demo-products/colors/brown.png' },
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
    ],
    href: '/products/robert-glasses',
  },
  {
    id: 'ZJGA463908-04',
    name: 'Patrick Glasses',
    price: 15.00,
    rating: 4.0,
    image: '/demo-products/product-3.jpg',
    colors: [
      { name: 'Yellow', hex: '#FFD700', img: '/demo-products/colors/gold.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
      { name: 'Yellow', hex: '#FFD700', img: '/demo-products/colors/gold.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
    ],
    href: '/products/patrick-glasses-yellow',
  },
  {
    id: 'ZJGA573577-02',
    name: 'George Glasses',
    price: 29.95,
    rating: 5.0,
    image: '/demo-products/product-4.jpg',
    colors: [
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
      { name: 'Green', hex: '#228B22', img: '/demo-products/colors/green.png' },
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
    ],
    href: '/products/george-glasses',
  },
  {
    id: 'ZJGA647256-01',
    name: 'Benjamin Glasses',
    price: 25.95,
    rating: 5.0,
    image: '/demo-products/product-5.jpg',
    colors: [
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
      { name: 'Two-tone', hex: '#333333', img: '/demo-products/colors/silver.png' },
    ],
    href: '/products/benjamin-glasses',
  },
  {
    id: 'ZJGX180481-01',
    name: 'Alexander Glasses',
    price: 39.95,
    rating: 5.0,
    image: '/demo-products/product-6.jpg',
    colors: [
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
      { name: 'Blue', hex: '#0000FF', img: '/demo-products/colors/blue.png' },
    ],
    href: '/products/alexander-glasses',
  },
  {
    id: 'ZJGX409047-01',
    name: 'Griff Glasses',
    price: 39.95,
    rating: 5.0,
    image: '/demo-products/product-7.jpg',
    colors: [
      { name: 'Black', hex: '#000000', img: '/demo-products/colors/black.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
      { name: 'Green', hex: '#228B22', img: '/demo-products/colors/green.png' },
    ],
    href: '/products/griff-glasses',
  },
  {
    id: 'ZJGX267614-01',
    name: 'Penelope Glasses',
    price: 29.95,
    rating: 2.7,
    image: '/demo-products/product-8.jpg',
    colors: [
      { name: 'Gold', hex: '#FFD700', img: '/demo-products/colors/gold.png' },
      { name: 'Silver', hex: '#C0C0C0', img: '/demo-products/colors/silver.png' },
      { name: 'Tortoise', hex: '#8B4513', img: '/demo-products/colors/tortoise.png' },
    ],
    href: '/products/penelope-glasses',
  },
];
